name: oos_detection
services:
  backend:
    build:
      args:
        TORCH_VARIANT: cu124
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
